[build-system]
requires = ["setuptools>=61.0", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name="forestflow"
dynamic = ["version"]
authors = [
    { name="Jonas Chaves-Montero", email="jchaves@ifae.es" },
    { name="Andreu Font-Ribera", email="afont@ifae.es" },
    { name="Laura Cabayol-Garcia"},
]
maintainers = [
    { name="Jonas Chaves-Montero", email="jchaves@ifae.es" }, 
    { name="Andreu Font-Ribera", email="afont@ifae.es" },
]
description = "Emulator for Lyman-alpha 3D power spectrum"
readme = "README.md"
license = { text = "MIT" }
keywords = [
    "Lyman-alpha", "Cosmology", "Power Spectrum", "Emulator",
]
requires-python = ">= 3.12"
dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "emcee",
    "torch",
    "freia",
    "corner",
    "astropy",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific :: Cosmology/Astrophysics",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.12",
]

[tool.setuptools_scm]
version_scheme = "no-guess-dev"
local_scheme = "node-and-date"


[tool.setuptools.packages.find]
include = ["forestflow", "forestflow.*"]
namespaces = false

[project.urls]
Homepage="https://github.com/igmhub/ForestFlow"
Repository="https://github.com/igmhub/ForestFlow.git"
Issues="https://github.com/igmhub/ForestFlow/issues"
